[project]
name = "adventofcode"
version = "0.1.0"
description = "Solutions for Advent of Code challenges"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy", "advent-of-code-data"]
